# Generated by Django 4.1.5 on 2023-11-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0002_alter_innovation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='reason_for_denial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='innovation',
            name='response',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
