# Generated by Django 4.1.5 on 2023-04-10 17:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('total_value', models.DecimalField(decimal_places=3, max_digits=50)),
                ('project_status', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=255)),
                ('project_pi', models.CharField(max_length=255)),
                ('project_co_pi', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('date_from', models.DateField()),
                ('expected_completion_date', models.DateField()),
                ('project_member', models.TextField()),
                ('project_donor', models.TextField()),
                ('project_partner', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='project_documents/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
