# Generated by Django 4.1.5 on 2023-02-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
        ('project', '0002_member_email_partner_email_alter_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='innovation',
            field=models.ManyToManyField(blank=True, null=True, to='publication.innovation'),
        ),
        migrations.AddField(
            model_name='project',
            name='publication',
            field=models.ManyToManyField(blank=True, null=True, to='publication.publication'),
        ),
        migrations.AlterField(
            model_name='project',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='project_documents/%Y/%m/%d/'),
        ),
    ]
