# Generated by Django 4.1.5 on 2023-06-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_is_approved_alter_project_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
