# Generated by Django 4.1.5 on 2023-02-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_innovation_project_publication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='innovation',
        ),
    ]
