# Generated by Django 4.1.5 on 2023-07-07 07:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_project_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmbrellaProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('total_value', models.FloatField()),
                ('project_status', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=255)),
                ('project_lead', models.CharField(max_length=255)),
                ('project_co_lead', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('date_from', models.DateField()),
                ('expected_completion_date', models.DateField()),
                ('project_member', models.TextField()),
                ('project_donor', models.TextField()),
                ('project_partner', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='project_documents/%Y/%m/%d/')),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='umbrella_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.umbrellaproject'),
        ),
    ]
