# Generated by Django 4.1.5 on 2023-07-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_umbrella_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umbrellaproject',
            old_name='project_co_pi',
            new_name='project_co_lead',
        ),
        migrations.RenameField(
            model_name='umbrellaproject',
            old_name='project_pi',
            new_name='project_lead',
        ),
        migrations.AddField(
            model_name='project',
            name='reason_for_denial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='response',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='umbrella_project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.umbrellaproject'),
        ),
    ]
