# Generated by Django 4.1.5 on 2023-07-09 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_project_co_pi_umbrellaproject_project_co_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='umbrella_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.umbrellaproject'),
        ),
    ]
