# Generated by Django 4.1.5 on 2023-02-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='innovationmedia',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
