# Generated by Django 4.1.5 on 2023-04-10 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovationmedia',
            name='innovation',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='researcherinnovation',
            name='innovation',
        ),
        migrations.RemoveField(
            model_name='researcherinnovation',
            name='researcher',
        ),
        migrations.RemoveField(
            model_name='researcherpublication',
            name='author_rank',
        ),
        migrations.RemoveField(
            model_name='researcherpublication',
            name='author_type',
        ),
        migrations.RemoveField(
            model_name='researcherpublication',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='researcherpublication',
            name='researcher',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='isbn',
            new_name='doi',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='place_of_publication',
            new_name='journal_name',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_link',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='tags',
        ),
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='co_authors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='number_of_pages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='collection',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='license',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='AuthorRank',
        ),
        migrations.DeleteModel(
            name='AuthorType',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Innovation',
        ),
        migrations.DeleteModel(
            name='InnovationMedia',
        ),
        migrations.DeleteModel(
            name='License',
        ),
        migrations.DeleteModel(
            name='PublicationType',
        ),
        migrations.DeleteModel(
            name='Researcher',
        ),
        migrations.DeleteModel(
            name='ResearcherInnovation',
        ),
        migrations.DeleteModel(
            name='ResearcherPublication',
        ),
    ]
