# Generated by Django 4.1.5 on 2023-02-06 08:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovation',
            name='license',
        ),
        migrations.AddField(
            model_name='innovation',
            name='patent',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='InnovationMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media', models.FileField(blank=True, upload_to='innovation_media/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.innovation')),
            ],
        ),
    ]
