# Generated by Django 4.1.5 on 2023-02-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_project_innovation'),
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovationmedia',
            name='innovation',
        ),
        migrations.RemoveField(
            model_name='researcherinnovation',
            name='innovation',
        ),
        migrations.RemoveField(
            model_name='researcherinnovation',
            name='researcher',
        ),
        migrations.DeleteModel(
            name='Innovation',
        ),
        migrations.DeleteModel(
            name='InnovationMedia',
        ),
        migrations.DeleteModel(
            name='ResearcherInnovation',
        ),
    ]
