# Generated by Django 4.1.5 on 2023-03-05 07:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0002_remove_innovationmedia_innovation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='publication_link',
            new_name='publication_source',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='tags',
        ),
        migrations.AddField(
            model_name='publication',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='publications/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='PublicationAuthors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('author_rank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.authorrank')),
                ('publication_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.publication')),
            ],
        ),
    ]
