# Generated by Django 4.1.5 on 2023-06-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_remove_innovationmedia_innovation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='publication/'),
        ),
    ]
