# Generated by Django 4.1.5 on 2023-02-20 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_innovation_description_innovationmedia_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.innovation')),
            ],
        ),
    ]
