# Generated by Django 4.1.5 on 2023-03-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_rename_publication_link_publication_publication_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publisher_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
