# Generated by Django 4.1.5 on 2023-02-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_innovationauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='year_of_innovation',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
