# Generated by Django 4.1.5 on 2023-06-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_publication_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='reason_for_denial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='response',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
