# Generated by Django 4.1.5 on 2023-03-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_alter_publication_publisher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
