# Generated by Django 4.1.5 on 2023-02-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_innovation_year_of_innovation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InnovationAuthor',
            new_name='Innovator',
        ),
    ]
