# Generated by Django 4.1.5 on 2023-03-05 08:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0005_alter_publication_isbn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicationAuthors',
            new_name='PublicationAuthor',
        ),
    ]
