# Generated by Django 4.1.5 on 2023-11-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='category',
            field=models.CharField(choices=[('grant', 'Grant'), ('project', 'Project'), ('consultancy', 'Consultancy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='call',
            name='document',
            field=models.FileField(upload_to='calls'),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='Open', max_length=50),
        ),
    ]
